- name: Check if font exits
  shell: fc-list | grep "JetBrainsMono Nerd" | wc -l
  register: font_output

- name: JetBrains Mono
  when: font_output.stdout == "0"
  block:
    - name: Create temporary directory
      tempfile:
        state: directory
        suffix: fonts
      register: download_dir

    - name: Download JetBrains Nerd Font
      get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip"
        dest: "{{ download_dir.path }}/JetBrainsMono.zip"

    - name: Create font dir
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.fonts"

    - name: Create JetBrains font dir
      file:
        state: directory
        path: "{{ ansible_env.HOME }}/.fonts/JetBrains"

    - name: Create extract dir
      file:
        state: directory
        path: "{{ download_dir.path }}/JetBrains"

    - name: Extract font
      unarchive:
        src: "{{ download_dir.path }}/JetBrainsMono.zip"
        dest: "{{ download_dir.path }}/JetBrains"

    - name: Move font
      copy:
        src: "{{ download_dir.path }}/JetBrains/"
        dest: "{{ ansible_env.HOME }}/.fonts/JetBrains"

    - name: Refresh font cache
      shell: fc-cache -vf
