- name: Create helm folder
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/programs/helm"


- name: Download helm
  get_url:
    url: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}/programs/helm"

- name: Unarchive helm
  unarchive:
    src: "{{ ansible_env.HOME }}/programs/helm/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}/programs/helm/"
    extra_opts:
      - "--strip-components=1"
      - "--no-wildcards"
      - "--no-anchored"
      - "helm"
- name: Rename helm
  copy:
    src: "{{ ansible_env.HOME }}/programs/helm/helm"
    dest: "{{ ansible_env.HOME }}/programs/helm/helm_{{ helm_version }}"
    mode: 0755

- name: Cleanup helm binary
  file:
    state: absent
    path: "{{ ansible_env.HOME }}/programs/helm/helm"
