- name: Create program folder
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/programs"

- name: Create local bin folder
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.local/bin"
    recurse: true

# Fonts

- name: Install fonts
  import_tasks: fonts.yaml
  tags:
    - fonts

# LunarVIM



# Helm

- name: Install helm
  include_tasks: helm.yaml
  loop: "{{ helm_versions }}"
  loop_control:
    loop_var: helm_version

- name: Create link to current version
  file:
    state: link
    path: "{{ ansible_env.HOME }}/programs/helm/helm"
    src: "{{ ansible_env.HOME }}/programs/helm/helm_{{ helm_current_version }}"

- name: Create link to version link
  file:
    state: link
    path: "{{ ansible_env.HOME }}/.local/bin/helm"
    src: "{{ ansible_env.HOME }}/programs/helm/helm"

# Kind

- name: Install kind
  include_tasks: kind.yaml
  loop: "{{ kind_versions }}"
  loop_control:
    loop_var: kind_version

- name: Create link to current version
  file:
    state: link
    path: "{{ ansible_env.HOME }}/programs/kind/kind"
    src: "{{ ansible_env.HOME }}/programs/kind/kind_{{ kind_current_version }}"

- name: Create link to version link
  file:
    state: link
    path: "{{ ansible_env.HOME }}/.local/bin/kind"
    src: "{{ ansible_env.HOME }}/programs/kind/kind"
