- name: Pre-setup
  hosts: localhost
  connection: local 
  roles:
    - role: pre-setup
      tags:
        - pre-setup

- name: Keys
  hosts: localhost
  connection: local 
  roles:
    - role: keys
      tags:
        - keys

- name: Sway
  hosts: localhost
  connection: local 
  roles:
    - role: sway
      tags:
        - sway

- name: Software
  hosts: localhost
  connection: local 
  roles:
    - role: software
      tags:
        - software

- name: dot files
  hosts: localhost
  connection: local 
  roles:
    - role: dotFiles
      tags:
        - dotfiles
