- name: APT
  hosts: localhost
  connection: local 
  roles:
    - role: apt
      tags:
        - apt

- name: Keys
  hosts: localhost
  connection: local 
  roles:
    - role: keys
      tags:
        - keys

- name: dot files
  hosts: localhost
  connection: local 
  roles:
    - role: dotFiles
      tags:
        - dotfiles
