- name: Fetch dotfiles
  git:
    repo: git@github.com:Xartos/dotfiles.git
    dest: "{{ ansible_env.HOME }}/privat/dotfiles"
    version: "main"

- name: Link config in .config
  file:
    state: link
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    src: "{{ ansible_env.HOME }}/privat/dotfiles/.config/{{ item }}"
  loop: "{{ dot_config_folders }}"

- name: Restart systemd units
  systemd:
    state: restarted
    scope: user
    daemon_reload: yes
    name: "{{ item }}"
  loop: "{{ dot_config_systemd_units }}"

- name: Copy bashrc
  copy:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    src: "{{ ansible_env.HOME }}/privat/dotfiles/.bashrc"

- name: Link bashrc directory
  file:
    state: link
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    src: "{{ ansible_env.HOME }}/privat/dotfiles/.bashrc.d"

- name: Copy gitconfig
  copy:
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    src: "{{ ansible_env.HOME }}/privat/dotfiles/.gitconfig"
