- name: Update and upgrade apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
  loop: "{{ apt_packages }}"

- name: Setup non password sudo
  become: true
  copy:
    src: files/50-freddeliv
    dest: /etc/sudoers.d/50-freddeliv
